### ISSUE TITLE
"graphical tools" ?

### ISSUE THREAD

**Issue by hansgru** [Swirrl/grafter#18]
You mention on the "The Grafter Vision" section that you plan to build "graphical tools"

Any details about that?

Is it something like a workflow editor in other ETL tools? e.g. 
http://type-exit.org/adventures-with-open-source-bi/2010/08/data-validation-and-monitoring-with-pentaho-kettle/

**Comment by RickMoynihan** [comment]
Hi,

The graphical tools we are planning are much more likely to follow the form of Google/OpenRefine than Kettle's graphical workflow environment.

We are aiming for simplicity, because we believe that turing complete graphical programming enivironments like Kettle are both too complicated for non-programmers, and too restrictive to like.

Basically, programmers like to use programming languages (and are essentially served by the Grafter API's) which can be used to express any computable transformation.  

We also believe that non-developers are best served by interactive spreadsheet like tools, that let this class of users develop simple transformations that encompass perhaps 80-90% of the transformations we commonly encounter.  

These users don't need explicit constructs for conditionals, looping, recursion etc... For them linear pipelines should be enough.

Additionally we believe that non-developer and developer pipelines should be shareable between communities, allowing for example a developer to call a pipeline built by the UI.

There is some additional discussion of the [rationale for Grafter](
http://blog.swirrl.com/articles/linked-data-etl/) on the Swirrl blog.
