### ISSUE TITLE
assoc-data-source-meta ignores existing metadata

### ISSUE THREAD

**Issue by lisp** [Swirrl/grafter#47]
if an encoding-specific method supplies metadata for a dataset, the logic in assoc-data-source-meta ignores it.

**Comment by RickMoynihan** [comment]
Thanks for reporting this.

Can you provide a specific example?

**Comment by lisp** [comment]
it has to do with adding support for weka .arff and logic to ensure that the header columns are pertinent.  
in this regard, the dataset is annotated to indicate whether the headers are canonical.
i observe that, when the dataset is then returned through the generic api operator, that annotation has been stripped.

here is a quick patch of the operator in question:

    (in-ns 'grafter.tabular.common)
    (defn assoc-data-source-meta [output-ds data-source]
      "Adds metadata about where the dataset was loaded from to the object."
      (let [source-meta (cond
                         (#{String File URI URL} (class data-source))  {:grafter.tabular/data-source data-source}
                         (instance? incanter.core.Dataset data-source) (meta data-source)
                         :else {:grafter.tabular/data-source :datasource-unknown}) ]
        (with-meta output-ds (merge (meta output-ds) source-meta))))

**Comment by RickMoynihan** [comment]
Thanks for filing this, I've incorporated your fix and added a test for it too.

Well done for figuring out how to add a new adapter, it's something we've been meaning to document.  
 
Are you planning on opensourcing the weka adapter?  If so I'm happy to add a link to it from the Grafter docs.

If you're not already signed up there is a Grafter-users mailing list: 

https://groups.google.com/forum/?hl=en-GB#!forum/grafter-users

I'd be curious to find out about your experiences with Grafter, and any comments you may have on how we can improve it.

**Comment by lisp** [comment]
once i am convinced that i have "figured it out" and am comfortable with how the source is arranged, the weka extension will find its way here : https://github.com/dydra/dydra.clj (or some equivalent outpost)

in general, despite your tutorials, when the intent is to put it to use, my impression is more that of a schrebergarten then jardin des tuileries, but at least it is all more or less within sight. that is, it is seems to be at a stage where it works quite well for your project, but there is still a ways to go until the organization is well enough exposed and the intent for every purpose more technical than a tutorial is well enough ratified, that someone coming in from the side knows they using things the way you intended, rather than just having figured out some way to make it work.

in this particular case, for example, there were some components which came and went over your versions and, while i think i now happen have eligible ones, in that they work with the 0.5.0 which i happen to be using, i have no reason to believe they will still be the right thing when you release your next version.

**Comment by RickMoynihan** [comment]
That's a fair assessment, we definitely want to do more restructuring and re-organising to make the intent clearer, and of course document the usage more.  This will inevitably mean breakages; and we do plan to break things in subsequent releases.  

I don't intend to change the backend for adapters much in the immediate future though; unless of course it proves inadequate for extension etc...

I hope to stage breaking changes into new releases to help managing porting code though; and helping people understand how things have changed.  So hopefully there won't be lots of significant breaking changes in a single release.  

There are lots of things that are currently undocumented; which is why if you have any questions or suggestions about the project and its direction you should ask on the mailing list.
